### PR TITLE
Handle errors gracefully, when extracting files. (Good for partially cor...

### PR DESCRIPTION
**Pull request by bashimao**
...rupted archives!)

Well, it does what it says. Added 3 lines for error checking to avoid the program from crashing if it faces a difficulty.

### CODE REVIEW

**Comment by Lattyware** [comment]
This seems like bad default behaviour - this should require a flag (continue on error or somesuch), and the exception information should come through standard syntax, not pulling it out of exc_info().

**Comment by TazeTSchnitzel** [comment]
Could the exception be somehow annotated?

**Comment by bashimao** [comment]
The default behavior right now is "silently crash". I am not sure if that is much better. However, since my code will (depending on the actual problem) print rather cryptic error messages, I agree that it might be worthwhile to wrap it into a command line argument. Do you have any wishes regarding what the command line argument should look like? How about:
 -p, --persistent   :     Ignore errors that occur while extracting files

**Comment by Lattyware** [comment]
I think descriptive is best, even if a little longer - I'd go with `--continue-on-error`.

**Comment by Lattyware** [comment]
Added as of latest.

**Pull request closed without merging**
